@host=http://localhost:5295

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNWE1YzE1YS03NDQwLTRlZjItOWEwMS1lY2M2MDA4ZWMxZDYiLCJnaXZlbl9uYW1lIjoiTWljaGFlbCBKb2huIiwiZmFtaWx5X25hbWUiOiJSaWVzZXIiLCJqdGkiOiIxNzdiZmYyMC0xZmRkLTQzNmYtYTFjMy01MTQzMGFjMmExN2UiLCJleHAiOjE3NTc4Nzc3ODAsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.jXuBcJ_JkXvGSFPjDV9tw8qEQXrWLjg53qssrdeiBuk